# .github/workflows/release.yaml

name: Build Release

on:
  push:
    branches: [ migration, dev ]
  pull_request:
    branches: [ canary, main ]
    
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'nhost'
            name: 'nhost'
            compress: 'false'
            dest: 'bin'