# .github/workflows/release.yaml

name: Release

on:
  #release:
    #types: # This configuration does not affect the page_build event above
      #- created
  push:
    tags:
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  releases-matrix:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin 
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set VERSION env
        run: |
          echo VERSION=$(basename ${GITHUB_REF}) >> ${GITHUB_ENV}
          echo $(basename ${GITHUB_REF})

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
            
      - name: Generate Binary
        uses: wangyoucao577/go-release-action@v1.20
        with:
          overwrite: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          # binary_name: cli
          ldflags: -X "github.com/${{ github.repository }}/cmd.Version=${{ env.VERSION }}" -X "github.com/${{ github.repository }}/nhost.REPOSITORY=${{ github.repository }}"

      #- name: Notify Community
        #uses: sarisia/actions-status-discord@v1
        #with:
          #webhook: ${{ secrets.DISCORD_WEBHOOK }}
          #nodetail: true
          #title: CLI ${{ env.VERSION }} Realeased
          #description: Upgrade using `nhost upgrade`