# .github/workflows/release.yaml

name: Build Release

on:
  push:
    branches: [ migration, dev ]
  pull_request:
    branches: [ canary, main ]
    
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        github_token: ${{ secrets.ACTIONS_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: 1.16
        binary_name: nhost
        extra_files: LICENSE